In [1]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)

In [4]:
arr[0:, 2:3] = 1 
print(arr)

[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]
 [21 22  1 24 25]]

In [7]:
arr1=np.random.randint(1,36,size=(6,6))
print(arr1)
print("ans")
print(arr1[2:5,1:4])

[[27 19 20 30 16 25]
 [ 4 19 21  3 29 21]
 [11  7 35 14 14  2]
 [ 1 32  9 15  5 30]
 [30  9 34 21 24 16]
 [27 12  9 10 26  7]]
ans
[[ 7 35 14]
 [32  9 15]
 [ 9 34 21]]

In [ ]:
arr2=np.random.randint(1,25,size=(5,5))
print(arr2)
print("answer")
print(arr2[])

In [8]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]

In [2]:
import pandas as pd

In [6]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df.head())
print("tails data")
print(df.tail())

          Name  Age       City         Occupation
0  Amit Sharma   28      Delhi  Software Engineer
1  Priya Verma   24     Mumbai             Doctor
2  Rahul Singh   30    Lucknow            Teacher
3  Sneha Gupta   27     Jaipur           Designer
4  Arjun Patel   35  Ahmedabad        Businessman
tails data
             Name  Age      City  Occupation
45  Akash Chauhan   28    Meerut      Driver
46  Preeti Chawla   33   Panipat  Beautician
47    Ravi Shukla   37      Rewa  Contractor
48   Pankaj Verma   34  Bareilly  Pharmacist
49    Geeta Yadav   29  Azamgarh      Tailor

In [8]:
df['Name']

0            Amit Sharma
1            Priya Verma
2            Rahul Singh
3            Sneha Gupta
4            Arjun Patel
5            Neha Kapoor
6            Vikas Yadav
7           Pooja Mishra
8              Rohit Das
9           Anjali Mehta
10        Karan Malhotra
11           Simran Kaur
12         Manish Tiwari
13          Kavita Joshi
14          Deepak Kumar
15            Shreya Sen
16         Nitin Agarwal
17           Ritu Saxena
18         Sandeep Reddy
19            Meena Iyer
20            Harsh Jain
21           Ayesha Khan
22         Gaurav Pandey
23           Nisha Arora
24           Rajesh Nair
25        Swati Kulkarni
26        Abhishek Singh
27           Divya Bhatt
28          Ramesh Gowda
29         Pallavi Desai
30    Saurabh Chatterjee
31            Ishita Roy
32           Prakash Jha
33            Tanvi Shah
34         Aditya Pillai
35           Komal Verma
36           Yash Thakur
37            Farhan Ali
38          Ritika Sinha
39             Mohan Lal
40            Ankita Das
41           Vivek Dubey
42            Rekha Devi
43          Tarun Bansal
44          Sonia Thomas
45         Akash Chauhan
46         Preeti Chawla
47           Ravi Shukla
48          Pankaj Verma
49           Geeta Yadav
Name: Name, dtype: object

In [9]:
df

                  Name  Age        City            Occupation
0          Amit Sharma   28       Delhi     Software Engineer
1          Priya Verma   24      Mumbai                Doctor
2          Rahul Singh   30     Lucknow               Teacher
3          Sneha Gupta   27      Jaipur              Designer
4          Arjun Patel   35   Ahmedabad           Businessman
5          Neha Kapoor   22  Chandigarh               Student
6          Vikas Yadav   31       Patna        Police Officer
7         Pooja Mishra   26    Varanasi        Content Writer
8            Rohit Das   29     Kolkata          Data Analyst
9         Anjali Mehta   25       Surat            HR Manager
10      Karan Malhotra   33       Delhi                Lawyer
11         Simran Kaur   28    Amritsar                 Nurse
12       Manish Tiwari   36      Bhopal    Government Officer
13        Kavita Joshi   27        Pune       Software Tester
14        Deepak Kumar   32      Ranchi           Electrician
15          Shreya Sen   23     Kolkata               Student
16       Nitin Agarwal   34      Kanpur            Shop Owner
17         Ritu Saxena   29       Noida     Marketing Manager
18       Sandeep Reddy   31   Hyderabad              Engineer
19          Meena Iyer   26     Chennai               Teacher
20          Harsh Jain   28      Indore  Chartered Accountant
21         Ayesha Khan   24      Mumbai         Makeup Artist
22       Gaurav Pandey   35   Allahabad             Professor
23         Nisha Arora   27    Ludhiana      Fashion Designer
24         Rajesh Nair   40       Kochi         Hotel Manager
25      Swati Kulkarni   30      Nagpur                Banker
26      Abhishek Singh   29   Gorakhpur       Sales Executive
27         Divya Bhatt   25    Dehradun          Photographer
28        Ramesh Gowda   38   Bangalore                Farmer
29       Pallavi Desai   33    Vadodara          Entrepreneur
30  Saurabh Chatterjee   36     Kolkata            Journalist
31          Ishita Roy   22    Siliguri               Student
32         Prakash Jha   41       Patna              Director
33          Tanvi Shah   28   Ahmedabad             Architect
34       Aditya Pillai   34  Trivandrum             Scientist
35         Komal Verma   26      Raipur               Teacher
36         Yash Thakur   31      Shimla            Tour Guide
37          Farhan Ali   29     Aligarh              Mechanic
38        Ritika Sinha   24     Dhanbad               Student
39           Mohan Lal   45     Jodhpur            Shopkeeper
40          Ankita Das   27    Guwahati                 Nurse
41         Vivek Dubey   32       Satna                 Clerk
42          Rekha Devi   39        Gaya             Homemaker
43        Tarun Bansal   35       Hisar           Businessman
44        Sonia Thomas   30    Kottayam               Teacher
45       Akash Chauhan   28      Meerut                Driver
46       Preeti Chawla   33     Panipat            Beautician
47         Ravi Shukla   37        Rewa            Contractor
48        Pankaj Verma   34    Bareilly            Pharmacist
49         Geeta Yadav   29    Azamgarh                Tailor

In [10]:
df.describe()

             Age
count  50.000000
mean   30.500000
std     5.159695
min    22.000000
25%    27.000000
50%    29.500000
75%    34.000000
max    45.000000

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("data.csv")
df.isnull()

     Name    Age   City  Occupation
0   False  False  False       False
1   False  False  False       False
2   False  False  False       False
3   False  False  False       False
4   False  False  False       False
5   False  False  False       False
6   False  False  False       False
7   False  False  False       False
8   False  False  False       False
9   False  False  False       False
10  False  False  False       False
11  False  False  False       False
12  False  False  False       False
13  False  False  False       False
14  False  False  False       False
15  False  False  False       False
16  False  False  False       False
17  False  False  False       False
18  False  False  False       False
19  False  False  False       False
20  False  False  False       False
21  False  False  False       False
22  False  False  False       False
23  False  False  False       False
24  False  False  False       False
25  False  False  False       False
26  False  False  False       False
27  False  False  False       False
28  False  False  False       False
29  False  False  False       False
30  False  False  False       False
31  False  False  False       False
32  False  False  False       False
33  False  False  False       False
34  False  False  False       False
35  False  False  False       False
36  False  False  False       False
37  False  False  False       False
38  False  False  False       False
39  False  False  False       False
40  False  False  False       False
41  False  False  False       False
42  False  False  False       False
43  False  False  False       False
44  False  False  False       False
45  False  False  False       False
46  False  False  False       False
47  False  False  False       False
48  False  False  False       False
49  False  False  False       False

In [4]:
df.isnull().sum()

Name          0
Age           0
City          0
Occupation    0
dtype: int64